//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransferAuthorizationService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Approver
    {
        public int Id { get; set; }
        public string Approver1 { get; set; }
        public string ApproverDeviceToken { get; set; }
    }
}
