//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransferAuthorizationService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int Id { get; set; }
        public string NetworkId { get; set; }
        public string Password { get; set; }
        public string NameFirst { get; set; }
        public string NameLast { get; set; }
        public string DeviceToken { get; set; }
        public string Title { get; set; }
    }
}
