//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransferAuthorizationDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AchAuthorization
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string AccountNumber { get; set; }
        public string Notes { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string OriginatingSystem { get; set; }
        public Nullable<System.DateTime> IssuedOn { get; set; }
        public Nullable<bool> IsApproved { get; set; }
    }
}
